schema_version: 1

context:
  name: vcs2l
  version: "1.1.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/vcs2l-${{ version }}.tar.gz
  sha256: e6b053d6371e4d7e196d2bdb6e729bd72a069310ad17246a6e0bf0660178cfae

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - vcs = vcs2l.commands.vcs:main
      - vcs-branch = vcs2l.commands.branch:main
      - vcs-bzr = vcs2l.commands.custom:bzr_main
      - vcs-custom = vcs2l.commands.custom:main
      - vcs-diff = vcs2l.commands.diff:main
      - vcs-export = vcs2l.commands.export:main
      - vcs-git = vcs2l.commands.custom:git_main
      - vcs-help = vcs2l.commands.help:main
      - vcs-hg = vcs2l.commands.custom:hg_main
      - vcs-import = vcs2l.commands.import_:main
      - vcs-log = vcs2l.commands.log:main
      - vcs-pull = vcs2l.commands.pull:main
      - vcs-push = vcs2l.commands.push:main
      - vcs-remotes = vcs2l.commands.remotes:main
      - vcs-status = vcs2l.commands.status:main
      - vcs-svn = vcs2l.commands.custom:svn_main
      - vcs-validate = vcs2l.commands.validate:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pyyaml
    - setuptools
  run_constraints:
    # vcstool was an earlier version of the project that was forked as vcs2l, so it install the same commands and it is incompatible,
    # see https://github.com/dirk-thomas/vcstool/issues/242#issuecomment-3233642467 and
    # https://conda-forge.org/docs/maintainer/adding_pkgs/#defining-conflicts
    - vcstool ==9999999999

tests:
  - python:
      imports:
        - vcs2l
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - vcs --help
      - vcs-branch --help
      - vcs-bzr --help
      - vcs-custom --help
      - vcs-diff --help
      - vcs-export --help
      - vcs-git --help
      - vcs-help --help
      - vcs-hg --help
      - vcs-import --help
      - vcs-log --help
      - vcs-pull --help
      - vcs-push --help
      - vcs-remotes --help
      - vcs-status --help
      - vcs-svn --help
      - vcs-validate --help

about:
  summary: vcs2l provides a command line tool to invoke vcs commands on multiple repositories.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/ros-infrastructure/vcs2l

extra:
  recipe-maintainers:
    - traversaro
